### ISSUE TITLE
Error in the help file

### ISSUE THREAD

**Issue by leandrovianna** [sollidsnake/verun#1]
Hi, the help file of VERun says to add arguments to build command, simply change the variable VEGppArgs (https://github.com/sollidsnake/verun/blob/master/doc/verun.txt#L37), but is not working. I tried the command: `let w:VEGppArgs="-std=c99"` and was not added to the command line. I then tested `:let w:VEGppArg="-std=c99"`, without the s, that worked. In the help file, the name of variable is wrong.

**Comment by sollidsnake** [comment]
I renamed VEGppArg to VEGppArgs. Now it should work as stated in the docs. Thanks for the report. Please reopen if you still have trouble
